force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Recently_Created__c.field-meta.xml
<CustomField>
    <fullName>Recently_Created__c</fullName>
    <formula>DATEVALUE(CreatedDate) &gt;= TODAY() - 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Recently Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PromptTemplateBatchGen.cls
public without sharing class PromptTemplateBatchGen {
    
    public static void submitBatch() {
        
        AiJobRun jobRun = new AiJobRun(
            JobType = 'PromptTemplate',
            Target  = 'Generate_Plot_Summary', // prompt template DeveloperName (Id also accepted)
            Status  = 'New'
        );
        insert as user jobRun;
        
        List<Movie__c> movies = [SELECT Id FROM Movie__c where Recently_Created__c = true];
        
        List<AiJobRunItem> items = new List<AiJobRunItem>();
        for (Movie__c m : movies) {
            Map<String, Object> payload = new Map<String, Object>{
                'Input:movieRecord' => new Map<String, Object>{ 'id' => m.Id }
            };
                items.add(new AiJobRunItem(
                    AiJobRunId = jobRun.Id,
                    Status     = 'Ready',
                    Input      = JSON.serialize(payload)
                ));
        }
        insert as user items;
        
        jobRun.Status = 'ReadyToStart';
        update as user jobRun;
        
    }
    
    
    
}